apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhasach-php
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nhasach-php
  template:
    metadata:
      labels:
        app: nhasach-php
    spec:
      containers:
        - name: app
          image: nginx:stable   # CI sẽ set lại image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nhasach-php
  namespace: default
spec:
  selector:
    app: nhasach-php
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
